### ISSUE TITLE
创建一个 primpt 异常 

### ISSUE THREAD

**Issue by deTian0** [pezzolabs/pezzo#183]
### Report

我在创建 prompt 的时候 后台报了一个错误。日志如下 
I reported an error in the background while creating prompt. Log as follows

### Expected behavior

正常创建

### Steps to reproduce the problem

1.创建一个项目
2.创建一个 prompt
3.前端显示 服务器内部错误。后端错误日志如下

1. Create a project
2. Create a prompt
3. The front-end displays an internal server error. Back-end error logs are as follows

 

### Logs (if applicable)

```
pezzo-main-pezzo-server-1   | INFO [09:34:49.743] ([Redacted]): Creating prompt version
pezzo-main-pezzo-server-1   |     requestId: "bb395f32-cf12-4a19-adc0-75894de8189f"
pezzo-main-pezzo-server-1   |     userId: "b28762e0-6928-4862-8576-89c81d28c66c"
pezzo-main-pezzo-server-1   |     content: {
pezzo-main-pezzo-server-1   |       "prompt": "Generate {numFacts} facts about the following topic: \"{topic}\""
pezzo-main-pezzo-server-1   |     }
pezzo-main-pezzo-server-1   |     message: "01"
pezzo-main-pezzo-server-1   |     promptId: "clm4on97h0000qj2dfutag1br"
pezzo-main-pezzo-server-1   |     service: "OpenAIChatCompletion"
pezzo-main-pezzo-server-1   |     settings: {
pezzo-main-pezzo-server-1   |       "model": "gpt-3.5-turbo",
pezzo-main-pezzo-server-1   |       "temperature": 0.7,
pezzo-main-pezzo-server-1   |       "max_tokens": 256,
pezzo-main-pezzo-server-1   |       "top_p": 1,
pezzo-main-pezzo-server-1   |       "frequency_penalty": 0,
pezzo-main-pezzo-server-1   |       "presence_penalty": 0
pezzo-main-pezzo-server-1   |     }
pezzo-main-pezzo-server-1   | ERROR [09:34:49.760] ([Redacted]): Error creating prompt version
pezzo-main-pezzo-server-1   |     requestId: "bb395f32-cf12-4a19-adc0-75894de8189f"
pezzo-main-pezzo-server-1   |     userId: "b28762e0-6928-4862-8576-89c81d28c66c"
pezzo-main-pezzo-server-1   |     content: {
pezzo-main-pezzo-server-1   |       "prompt": "Generate {numFacts} facts about the following topic: \"{topic}\""
pezzo-main-pezzo-server-1   |     }
pezzo-main-pezzo-server-1   |     message: "Cannot read properties of undefined (reading 'track')"
pezzo-main-pezzo-server-1   |     promptId: "clm4on97h0000qj2dfutag1br"
pezzo-main-pezzo-server-1   |     service: "OpenAIChatCompletion"
pezzo-main-pezzo-server-1   |     settings: {
pezzo-main-pezzo-server-1   |       "model": "gpt-3.5-turbo",
pezzo-main-pezzo-server-1   |       "temperature": 0.7,
pezzo-main-pezzo-server-1   |       "max_tokens": 256,
pezzo-main-pezzo-server-1   |       "top_p": 1,
pezzo-main-pezzo-server-1   |       "frequency_penalty": 0,
pezzo-main-pezzo-server-1   |       "presence_penalty": 0
pezzo-main-pezzo-server-1   |     }
pezzo-main-pezzo-server-1   |     stack: "TypeError: Cannot read properties of undefined (reading 'track')\n    at AnalyticsService.trackEvent (/app/main.js:4807:28)\n    at PromptVersionsResolver.createPromptVersion (/app/main.js:7874:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)\n    at async /app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24"
pezzo-main-pezzo-server-1   |     error: {}

```

### Pezzo version

last

### How do you use Pezzo?

Docker Compose

**Comment by arielweinberger** [comment]
@deTian0 this was fixed in our recent release (today) - [v0.5.2](https://github.com/pezzolabs/pezzo/releases/tag/v0.5.2). Should be live on Pezzo Cloud shortly. If you're running locally, make sure you refetch images in your compose file.
