### ISSUE TITLE
Entering a project dashboard crashes the UI and displays a blank page

### ISSUE THREAD

**Issue by michaeltastewise** [pezzolabs/pezzo#319]
### Report

When entering my project's dashboard I am getting:
```
ClientError: Failed to get metric delta: {"response":{"errors":[{"message":"Failed to get metric delta","locations":[{"line":2,"column":3}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}],"data":null,"status":200,"headers":{}},"request":{"query":"query getProjectMetricDelta($data: GetProjectMetricDeltaInput!) {\n  projectMetricDelta(data: $data) {\n    currentValue\n    previousValue\n  }\n}","variables":{"data":{"projectId":"clsvmma460c771k0hgkep7c26","metric":"TotalRequests","startDate":"2024-09-28T10:54:26.081Z","endDate":"2024-09-29T10:54:26.081Z"}}}}
    at s_ (index.ts:426:11)
```

It seems like something changed lately.

### Expected behavior

To display my prompts

### Steps to reproduce the problem

1. Log in
2. Go into a project
3. Crash

### Logs (if applicable)

```
ClientError: Failed to get metric delta: {"response":{"errors":[{"message":"Failed to get metric delta","locations":[{"line":2,"column":3}],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}],"data":null,"status":200,"headers":{}},"request":{"query":"query getProjectMetricDelta($data: GetProjectMetricDeltaInput!) {\n  projectMetricDelta(data: $data) {\n    currentValue\n    previousValue\n  }\n}","variables":{"data":{"projectId":"clsvmma460c771k0hgkep7c26","metric":"TotalRequests","startDate":"2024-09-28T10:54:26.081Z","endDate":"2024-09-29T10:54:26.081Z"}}}}
    at s_ (index.ts:426:11)
```

### How do you use Pezzo?

Pezzo Cloud

**Comment by ANSUJKMEHER** [comment]
Hi! I'd like to work on this issue. I'll investigate the root cause and submit a fix if I can reproduce it.
